tracker_app/routes.py
import flask
from flask import Blueprint, render_template, redirect, url_for, flash, make_response, request
from tracker_app.config import Config
import functools
from authlib.integrations.requests_client import OAuth2Session
import google.oauth2.credentials
import googleapiclient.discovery
from tracker_app.user_manager import check_if_user_exists, create_user, get_user_data, change_name
from tracker_app.forms import UpdateUserSettings, NewLocation, NewFlight
from tracker_app.location_manager import get_country_from_coordinates, add_location_to_db, get_locations_from_db, \
    get_location_coordinates, delete_location_from_db, check_location_id_belongs_to_user, get_location_from_coordinates, \
    add_flight_to_db, get_flights_from_db, get_flight_coordinates, \
    check_flight_id_belongs_to_user, delete_flight_from_db


tracker = Blueprint("tracker", __name__)


@tracker.route("/", methods=["GET", "POST"])
def home():
    if is_logged_in():
        user_info = get_user_info()
        if check_if_user_exists(user_info['email']) is False:
            create_user(user_info['email'], user_info['given_name'])

        location_info = get_location_coordinates(user_info['email'])
        flight_info = get_flight_coordinates(user_info['email'])
        return render_template("home.html", title="Home", api_key=Config.API_KEY, location_info=location_info,
                               flight_info=flight_info, name=user_info['given_name'],
                               email=user_info['email'], logged_in=True)

    flash("You need to login!", "info")
    return render_template("home.html", title="Home", logged_in=False)


@tracker.route("/settings", methods=["GET", "POST"])
def settings():
    if is_logged_in():
        user_info = get_user_info()
        if check_if_user_exists(user_info['email']):
            data = get_user_data(user_info['email'])

            form = UpdateUserSettings()
            form.username.data = data["name"]
            if form.validate_on_submit():
                if form.username.raw_data[0] != data["name"]:
                    change_name(data["email"], form.username.raw_data[0])
                else:
                    flash("You haven't made any changes to your settings.", "info")
                return redirect(url_for("tracker.settings"))

            return render_template("settings.html", title="Settings", logged_in=True, form=form,
                                   email=data["email"], name=data["name"], color=data["color"])

    flash("Unable to access settings without being logged in!", "danger")
    return redirect(url_for("tracker.home"))


@tracker.route("/locations", methods=["GET", "POST"])
def locations():
    if is_logged_in():
        user_info = get_user_info()

        if check_if_user_exists(user_info['email']):
            data = get_locations_from_db(user_info['email'])
            number_of_locations = len(data)
            return render_template("locations.html", title="Locations", logged_in=True,
                                   number_of_locations=number_of_locations, data=data)

    flash("Unable to access the location page without being logged in!", "danger")
    return redirect(url_for("tracker.home"))


@tracker.route("/locations/add", methods=["GET", "POST"])
def add_location():
    if is_logged_in():
        user_info = get_user_info()

        if check_if_user_exists(user_info['email']):
            return render_template("add_location.html", title="Add Location", logged_in=True, api_key=Config.API_KEY)

    flash("Unable to access the location page without being logged in!", "danger")
    return redirect(url_for("tracker.home"))


@tracker.route("/locations/confirm", methods=["GET", "POST"])
def confirm_add_location():
    lat = request.args.get('lat')
    lng = request.args.get('lng')

    if not lat or not lng:
        flash("Sorry. We couldn't reach that location.")
        return redirect(url_for("tracker.locations"))

    if is_logged_in():
        user_info = get_user_info()
        if check_if_user_exists(user_info['email']):
            country = get_country_from_coordinates(lat, lng)
            if not country:
                return redirect(url_for("tracker.locations"))

            form = NewLocation()
            if form.validate_on_submit():
                add_location_to_db(user_info['email'], form.name.data, country, form.description.data,
                                   lat, lng, form.pin_color.data)
                return redirect(url_for("tracker.locations"))

            return render_template("confirm_location.html", title="Confirm Location", logged_in=True,
                                   country=country, form=form)

    flash("Unable to access the location page without being logged in!", "danger")
    return redirect(url_for("tracker.home"))


@tracker.route("/locations/delete/<location_id>", methods=["GET", "POST"])
def delete_location(location_id):
    if is_logged_in():
        user_info = get_user_info()
        if check_location_id_belongs_to_user(user_info['email'], location_id):
            delete_location_from_db(location_id)
        else:
            flash("This location's ID is invalid.", "danger")
    return redirect(url_for("tracker.locations"))


@tracker.route("/flights", methods=["GET", "POST"])
def flights():
    if is_logged_in():
        user_info = get_user_info()

        if check_if_user_exists(user_info['email']):
            data = get_flights_from_db(user_info['email'])
            number_of_flights = len(data)
            return render_template("flights.html", title="Flights", logged_in=True,
                                   data=data, number_of_flights=number_of_flights)

    flash("Unable to access the flights page without being logged in!", "danger")
    return redirect(url_for("tracker.home"))


@tracker.route("/flights/add", methods=["GET", "POST"])
def add_flight():
    if is_logged_in():
        user_info = get_user_info()
        if check_if_user_exists(user_info['email']):
            return render_template("add_flight.html", title="Add Flight", logged_in=True, api_key=Config.API_KEY)

    flash("Unable to access the flights page without being logged in!", "danger")
    return redirect(url_for("tracker.home"))


@tracker.route("/flights/confirm", methods=["GET", "POST"])
def confirm_flight():
    lat1 = request.args.get('lat1')
    lng1 = request.args.get('lng1')
    lat2 = request.args.get('lat2')
    lng2 = request.args.get('lng2')

    if not lat1 or not lng1 or not lat2 or not lng2:
        flash("Sorry. We couldn't log that flight.")
        return redirect(url_for("tracker.flights"))

    if is_logged_in():
        user_info = get_user_info()
        if check_if_user_exists(user_info['email']):
            loc1 = get_location_from_coordinates(lat1, lng1)
            loc2 = get_location_from_coordinates(lat2, lng2)

            if not loc1 or not loc2:
                flash("Unable to access that specific location.", "danger")
                return redirect(url_for("tracker.flights"))

            form = NewFlight()
            if form.validate_on_submit():
                add_flight_to_db(user_info['email'], form.flight_name.data, loc1, lat1, lng1, loc2, lat2, lng2)
                return redirect(url_for("tracker.flights"))

            return render_template("confirm_flight.html", title="Confirm Flight", logged_in=True, form=form, loc1=loc1,
                                   loc2=loc2)

    flash("Unable to access the flights page without being logged in!", "danger")
    return redirect(url_for("tracker.home"))


@tracker.route("/flights/delete/<flight_id>", methods=["GET", "POST"])
def delete_flight(flight_id):
    if is_logged_in():
        user_info = get_user_info()
        if check_flight_id_belongs_to_user(user_info['email'], flight_id):
            delete_flight_from_db(flight_id)
        else:
            flash("This flight ID is invalid.", "danger")
    return redirect(url_for("tracker.flights"))


def is_logged_in():
    return True if Config.AUTH_TOKEN_KEY in flask.session else False


def build_credentials():
    if not is_logged_in():
        raise Exception('User must be logged in')

    oauth2_tokens = flask.session[Config.AUTH_TOKEN_KEY]

    return google.oauth2.credentials.Credentials(
        oauth2_tokens['access_token'],
        refresh_token=oauth2_tokens['refresh_token'],
        client_id=Config.CLIENT_ID,
        client_secret=Config.CLIENT_SECRET,
        token_uri=Config.ACCESS_TOKEN_URI)


def get_user_info():
    credentials = build_credentials()

    oauth2_client = googleapiclient.discovery.build(
                        'oauth2', 'v2',
                        credentials=credentials)

    return oauth2_client.userinfo().get().execute()


def no_cache(view):
    @functools.wraps(view)
    def no_cache_impl(*args, **kwargs):
        response = make_response(view(*args, **kwargs))
        response.headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
        response.headers['Pragma'] = 'no-cache'
        response.headers['Expires'] = '-1'
        return response

    return functools.update_wrapper(no_cache_impl, view)


@tracker.route('/google/login')
@no_cache
def login():
    session = OAuth2Session(Config.CLIENT_ID, Config.CLIENT_SECRET,
                            scope=Config.AUTHORIZATION_SCOPE,
                            redirect_uri=Config.AUTH_REDIRECT_URI)

    uri, state = session.create_authorization_url(Config.AUTHORIZATION_URL)

    flask.session[Config.AUTH_STATE_KEY] = state
    flask.session.permanent = True

    return redirect(uri, code=302)


@tracker.route('/google/auth')
@no_cache
def google_auth_redirect():
    req_state = request.args.get('state', default=None, type=None)

    if req_state != flask.session[Config.AUTH_STATE_KEY]:
        response = make_response('Invalid state parameter', 401)
        return response

    session = OAuth2Session(Config.CLIENT_ID, Config.CLIENT_SECRET,

tracker_app/templates/add_flight.html
{% include "header.html" %}
{% block content %}
    <br>
    <div class="row justify-content-center">
        <h3>Search the airport you flew from, then the airport you flew to:</h3>
    </div>
    <br>

    <div id="map"></div>
    <input id="pac-input" class="controls" type="text" placeholder="Search Box">

    <script>

        var map;
        var infowindow;

        function initMap() {
            infowindow = new google.maps.InfoWindow();

            map = new google.maps.Map(
                document.getElementById('map'), {
                    center: {lat: 40, lng: 0},
                    zoom: 2
                });

            var input = document.getElementById('pac-input');
            var searchBox = new google.maps.places.SearchBox(input);
            map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

            map.addListener('bounds_changed', function () {
                searchBox.setBounds(map.getBounds());
            });


            var markers = [];
            var coordinates = [];

            searchBox.addListener('places_changed', function () {
                var places = searchBox.getPlaces();

                if (places.length == 0) {
                    return;
                }


                places.forEach(function (place) {
                    if (!place.geometry) {
                        console.log("Returned place contains no geometry");
                        return;
                    }

                    // Create a marker for each place.
                    markers.push(new google.maps.Marker({
                        map: map,
                        icon: "http://maps.google.com/mapfiles/kml/pal2/icon48.png",
                        title: place.name,
                        position: place.geometry.location
                    }));

                    coordinates.push([place.geometry.location.lat(), place.geometry.location.lng()])
                });
                document.getElementById('pac-input').value = '';

                if(coordinates.length >= 2){
                    window.location.replace("http://127.0.0.1:5000/flights/confirm?lat1="+ coordinates[0][0] +
                        "&lng1=" + coordinates[0][1] + "&lat2=" + coordinates[1][0] + "&lng2=" + coordinates[1][1]);
                }
            });

        }

    </script>


{% endblock content %}
{% include "footer.html" %}

tracker_app/templates/add_location.html
{% include "header.html" %}
{% block content %}
    <br>
    <div class="row justify-content-center">
        <h2>Click anywhere to add a new location:</h2>
    </div>
        <br>
        <div id="map"></div>
        <script>
          var map;
          function initMap() {

            map = new google.maps.Map(document.getElementById('map'), {
              center: {lat: 40, lng: 0},
              zoom: 2
            });

              google.maps.event.addListener(map, 'click', function(event) {
                addMarker(event.latLng, map);


                  window.location.replace("http://127.0.0.1:5000/locations/confirm?lat=" + event.latLng.lat() + "&lng=" + event.latLng.lng());
              });

          }

          function addMarker(location, map) {

          var marker = new google.maps.Marker({
            position: location,
            map: map
          });
        }

        google.maps.event.addDomListener(window, 'load', initMap);

        </script>

{% endblock content %}
{% include "footer.html" %}

tracker_app/templates/confirm_flight.html
{% include "header.html" %}
{% block content %}

    <main role="main" class="container text-center">
        <br><br>
        <h3>Do you want to add this flight to your list?</h3><br>
        <a href="{{ url_for('tracker.add_flight') }}">
            <button type="submit" class="btn btn-primary">
                Cancel
            </button>
        </a>
        <br><br>

        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="content-section">

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Start Location</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1"
                               placeholder="{{ loc1 }}"
                               readonly>
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">End Location</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1"
                               placeholder="{{ loc2 }}"
                               readonly>
                    </div>
                    <br>
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <div class="form-group">
                                {{ form.flight_name.label(class="form-control-label") }}
                                {% if form.flight_name.errors %}}
                                    {{ form.flight_name(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.flight_name.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.flight_name(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                        </fieldset>
                        <div class="form-group">
                            {{ form.submit(class="btn btn-primary mb-2") }}
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </main>
    <br><br><br><br><br><br><br>
{% endblock content %}
{% include "footer.html" %}

tracker_app/templates/confirm_location.html
{% include "header.html" %}
{% block content %}

    <main role="main" class="container text-center">
        <br><br>
        <h3>Do you want to add this location to your list?</h3><br>
        <a href="{{ url_for('tracker.add_location') }}">
            <button type="submit" class="btn btn-primary">
                Cancel
            </button>
        </a>
        <br><br>

        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="content-section">

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Country</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="{{ country }}"
                               readonly>
                    </div><br>
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <div class="form-group">
                                {{ form.name.label(class="form-control-label") }}
                                {% if form.name.errors %}}
                                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.name.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.name(class="form-control form-control-lg") }}
                                {% endif%}
                            </div>
                        </fieldset>
                        <fieldset class="form-group">
                            <div class="form-group">
                                {{ form.description.label(class="form-control-label") }}
                                {% if form.description.errors %}}
                                    {{ form.description(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.description.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.description(class="form-control form-control-lg") }}
                                {% endif%}
                            </div>
                        </fieldset>
                        <fieldset class="form-group">
                            <div class="form-group">
                                {{ form.pin_color.label(class="form-control-label") }}
                                {% if form.pin_color.errors %}}
                                    {{ form.pin_color(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.pin_color.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.pin_color(class="form-control form-control-lg") }}
                                {% endif%}
                            </div>
                        </fieldset>

                        <div class="form-group">
                            {{ form.submit(class="btn btn-primary mb-2") }}
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </main>
    <br><br><br><br><br><br><br>
{% endblock content %}
{% include "footer.html" %}

tracker_app/templates/flash.html
<main role="main" class="container">

      <div class="row justify-content-center">
        <div class="col-lg-6">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <br><br><br>
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}

        {% block content %}{% endblock %}

        </div>
      </div>
</main>

tracker_app/templates/flights.html
{% include "header.html" %}
{% block content %}

    <main role="main" class="container text-center">
        <br><br>
        <h3>Your Flights:</h3>
        <br>
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="content-section">
                    {% if number_of_flights == 1 %}
                        <p>You currently have 1 flight added.</p><br>
                    {% else %}
                        <p>You currently have {{ number_of_flights }} flights added.</p><br>
                    {% endif %}
                    <br>
                    <a href="{{ url_for('tracker.add_flight') }}">
                        <button type="submit" class="btn btn-primary">
                            Add a Flight
                        </button>
                    </a>
                    <br><br><br><br>

                </div>
            </div>
        </div>
    </main>
    {% if number_of_flights > 0 %}
        <div class="container">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th scope="col">Flight Name</th>
                    <th scope="col">Start</th>
                    <th scope="col">End</th>
                    <th scope="col">Remove</th>
                </tr>
                </thead>
                <tbody>
                {% for flight in data %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        <th>{{ flight[2] }}</th>
                        <th>{{ flight[3] }}</th>
                        <th>{{ flight[6] }}</th>
                        <th><a href="{{ url_for("tracker.delete_flight", flight_id=flight[0]) }}">Delete</a></th>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}

    <br><br><br><br><br>
{% endblock content %}
{% include "footer.html" %}

tracker_app/templates/footer.html
    <script src="https://maps.googleapis.com/maps/api/js?key={{api_key}}&libraries=places&callback=initMap"
    async defer></script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

tracker_app/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 80%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        width:100%;
        margin: 0;
        padding: 0;
      }
    .controls {
    background-color: #fff;
    border-radius: 2px;
    border: 1px solid transparent;
    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
    box-sizing: border-box;
    font-family: Roboto;
    font-size: 15px;
    font-weight: 300;
    height: 29px;
    margin-left: 17px;
    margin-top: 10px;
    outline: none;
    padding: 0 11px 0 13px;
    text-overflow: ellipsis;
    width: 400px;
    }

    .controls:focus {
    border-color: #4d90fe;
    }
    .title {
    font-weight: bold;
    }
    #infowindow-content {
    display: none;
    }
    #map #infowindow-content {
    display: inline;
    }


    </style>

    <title>
        {% if title %}
            {{ title }} -
        {% endif %}
        Travel Tracker
    </title>
    <link rel="icon"
      type="image/png"
      href="https://cdn4.iconfinder.com/data/icons/aiga-symbol-signs/444/aiga_departingflights-512.png">

</head>

<body>

    <header class="site-header">

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-static-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll-trigger" href="{{ url_for('tracker.home') }}">Okto's Travel Tracker</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                {% if logged_in %}
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{{ url_for("tracker.home") }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{{ url_for("tracker.locations") }}">Locations</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{{ url_for("tracker.flights") }}">Flights</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{{ url_for('tracker.settings') }}">Settings</a>
                          <a class="dropdown-item" href="{{ url_for('tracker.logout') }}">Log Out</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{{ url_for('tracker.login') }}">Login</a>
                </li>
                {% endif %}
            </ul>
          </div>
        </div>
      </nav>
        {% include "flash.html" %}
    </header>

tracker_app/templates/locations.html
{% include "header.html" %}
{% block content %}

    <main role="main" class="container text-center">
        <br><br>
        <h3>Your locations:</h3>
        <br>
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="content-section">
                    {% if number_of_locations == 1 %}
                        <p>You currently have 1 location added.</p><br>
                    {% else %}
                        <p>You currently have {{ number_of_locations }} locations added.</p><br>
                    {% endif %}
                    <br>
                    <a href="{{ url_for('tracker.add_location') }}">
                    <button type="submit" class="btn btn-primary">
                        Find a Location
                    </button> </a>
                    <br><br><br><br>

                </div>
            </div>
        </div>
    </main>
    {% if number_of_locations > 0 %}
        <div class="container">
        <table class="table">
            <thead>
                <tr>
                  <th>#</th>
                  <th scope="col">Name</th>
                  <th scope="col">Description</th>
                  <th scope="col">Country</th>
                  <th scope="col">Remove</th>
                </tr>
            </thead>
            <tbody>
                {% for location in data %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        <th>{{ location[2] }}</th>
                        <th>{{ location[3] }}</th>
                        <th>{{ location[4] }}</th>
                        <th><a href="{{ url_for("tracker.delete_location", location_id=location[0]) }}">Delete</a></th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    {% endif %}
    <br><br><br><br><br>
{% endblock content %}
{% include "footer.html" %}

tracker_app/templates/settings.html
{% include "header.html" %}
{% block content %}

    <main role="main" class="container text-center">
        <br><br>
        <h3>Hello {{ name }}, here are your settings</h3>
        <br><br>
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="content-section">

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Your Email Address</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="{{ email }}"
                               readonly>
                    </div><br>

                    <form method="POST" action="">
                        {{ form.hidden_tag() }}

                        <fieldset class="form-group">
                            <label for="exampleFormControlInput1">Your Name</label>
                            <div class="form-group">
                                {% if form.username.errors %}}
                                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.email.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.username(class="form-control form-control-lg") }}
                                {% endif%}
                            </div>
                        </fieldset>

                        <div class="form-group">
                            {{ form.submit(class="btn btn-primary mb-2") }}
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </main>


{% endblock content %}
{% include "footer.html" %}